### ISSUE TITLE
Wrong video record orientation. 

### ISSUE THREAD

**Issue by objectorientedperson** [Ziggeo/Android-Client-SDK#17] opened 2018-01-17 21:42 UTC
Whenever I record and upload a video, my record has different orientation (upside down)

I checked the local file under file system and saw that the orientation is wrong. Here is the screenshot.

![screenshot_20180117-234017](https://user-images.githubusercontent.com/3332056/35068528-50f38e66-fba5-11e7-8059-dd5eb9e9d9dd.png)

**Comment by 3akat** [comment] 2018-01-18 13:34
@objectorientedperson can you please specify the device and android version?

**Comment by objectorientedperson** [comment] 2018-01-19 16:10
@3akat Android 7.1 - Motorola Nexus 6

**Comment by objectorientedperson** [comment] 2018-02-02 17:28
@3akat Anything new?

**Comment by 3akat** [comment] 2018-02-04 19:00
Hi @objectorientedperson,
Unfortunately was unable to reproduce on any of my devices, will try to fix blindly.

**Comment by 3akat** [comment] 2018-02-06 04:08
@objectorientedperson can you please try version `a420c47417`?

**Comment by Bane-D** [comment] 2018-02-19 15:31
@3akat Just wanted to let you know that I had checked all of our channels and no one else was reporting such issues. LG is one of the common marks of devices that tests are done on as well so it is possible that there was something specific happening.

I suggest closing it by the end of the week as solved. @objectorientedperson please let us know before in case you are still experiencing any similar experience as your original report.

**Comment by sagrawal31** [comment] 2020-03-09 11:46
Hi, @Bane-D I was about to create an issue and I found this. I'm facing this exact same issue. And the thing is that I can reproduce it constantly without a hitch.

Can we reopen it to discuss more?

**Comment by 3akat** [comment] 2020-03-09 12:00
@sagrawal31 done! Please add more info if you have something :)

**Comment by sagrawal31** [comment] 2020-03-09 12:20
Like we have been discussing over the email 😄we have written a Cordova plugin https://github.com/wizpanda/cordova-plugin-ziggeo and is stabilizing it. 

In the start, I was thinking that this issue of wrong orientation (180 degrees rotated) is because of some misconfiguration in the Cordova plugin code. But later I figured out that, it is only happening when we are explicitly setting the `facing` to front camera through the following code:

```
builder.facing(CameraView.FACING_FRONT);
```

When this flag is not set (i.e. back camera is being used), this issue is not happening. (I have not tried by manually switch the camera).

**Comment by sagrawal31** [comment] 2020-03-09 12:34
This can be easily reproduced by setting the line `builder.facing(CameraView.FACING_FRONT)` in this demo app only.

**Comment by sagrawal31** [comment] 2020-03-09 12:44
https://stackoverflow.com/questions/29609838/nullpointerexception-from-mediaplayer-onpause-looses-reference this helps?

**Comment by 3akat** [comment] 2020-03-09 12:48
will check everything, thanks!

**Comment by sagrawal31** [comment] 2020-03-10 12:33
Any solution/workaround for this to fix?

**Comment by sagrawal31** [comment] 2020-03-10 12:34
Sorry to rush because our app is recording only with the front camera only as it is an assessment test app.

**Comment by 3akat** [comment] 2020-03-10 13:58
Please take a look at 0.82.4

**Comment by sagrawal31** [comment] 2020-03-10 16:01
That's so fast 😄 This issue is actually fixed now. Thank you for the quick resolution. Please close this issue again.

By the way, what was the problem? Why using front camera was recording in reverse orientation?

**Comment by 3akat** [comment] 2020-03-10 16:04
Great to hear that!
The problem is that camera orientation value is different from screen orientation. For example if screen orientation is `0` recorder should be configured with `90`. And the case was that for the from camera it should be `270` instead of `90`. 
In short - wrong calculation.

**Comment by sagrawal31** [comment] 2020-03-10 16:05
Thank you for the explanation @3akat

**Closed by 3akat** 2020-03-10 16:04 UTC
